export enum ErrorCode {
  VALIDATION = "VALIDATION",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  CATEGORY_NAME_ALREADY_IN_USE = "CATEGORY_NAME_ALREADY_IN_USE",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
}
